[package]
name = "shrine_backend_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
chrono = "0.4"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }